# Generated by Django 4.1.4 on 2022-12-16 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiverconsultationslot',
            name='parent',
        ),
        migrations.AlterField(
            model_name='caregiverspeciality',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialities', to='website.caregiver'),
        ),
    ]
