# Generated by Django 4.1.4 on 2022-12-28 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_caregiverconsultationslot_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiverconsultationslot',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_slots', to='website.caregiver'),
        ),
        migrations.AlterField(
            model_name='caregiverdiploma',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='website.caregiver'),
        ),
        migrations.AlterField(
            model_name='caregiverspeciality',
            name='speciality',
            field=models.CharField(choices=[('Certified Breastfeeding Specialist', 'Certified Breastfeeding Specialist'), ('HypnoBirthing® Childbirth Educator', 'HypnoBirthing® Childbirth Educator'), ('Midwife', 'Midwife'), ('Doula', 'Doula'), ('Lactation/breastfeeding consultant', 'Lactation/breastfeeding consultant'), ('Babywearing specialist', 'Babywearing specialist'), ('Sleep specialist', 'Sleep specialist'), ('Pediatrician', 'Pediatrician'), ('Perinatal psychologist', 'Perinatal psychologist'), ('Physical therapist', 'Physical therapist'), ('Pre/post natal yoga teacher', 'Pre/post natal yoga teacher'), ('Pre/post natal massage', 'Pre/post natal massage'), ('Baby massage', 'Baby massage'), ('Pre/post natal physical therapist', 'Pre/post natal physical therapist'), ('Osteopath', 'Osteopath'), ('Parenting coach', 'Parenting coach'), ('Psychomotrician', 'Psychomotrician')], max_length=240),
        ),
    ]
